### PR TITLE
Split `RollerConveyor` model and refactoring

### LINKED ISSUE #65: `Roller`s and `Sideguard`s do not properly transform with `RollerConveyorAssembly`
They phase through each other.

### PR DESCRIPTION
**Pull request by cooperra**
Split `RollerConveyor`'s models into left/right halves. This allows adjusting conveyor width without scaling edge parts width-wise, which looks weird.

Also includes a large refactor of `RollerConveyor` to rely on signals and to unify `Rollers` and `RollerConveyorEnd` with an abstract class. In retrospect, it probably relies on signals too much. At least it would be easy to convert them back to function calls while maintaining the abstraction benefits.

Fixes #65.

Also removes the use of Editable Children on `ConveyorAssembly`'s conveyor parts for #97.

### CODE REVIEW

**Comment by ryevdokimov** [comment]
image

The legs are readjusting when spawning a `RollerConveyorAssembly` and makes them merge into the side of the conveyor

**Comment by cooperra** [comment]
Fixed.

**Review by ryevdokimov — CHANGES_REQUESTED** [review]
image

Errors when spawning the assembly.

**Comment by cooperra** [comment]
I took a look at that earlier. It seems to be a regression with the side guards introduced in #93. Since I didn't touch any side guard code in this PR, I think we should solve it separately.

**Comment by cooperra** [comment]
Or at least, it was a good reason for me to ignore it while I worked on the rest of it.

**Review by ryevdokimov — APPROVED** [review]

**Comment by ryevdokimov** [comment]
Thanks!

**Pull request merged**
