### PR TITLE
ConveyorAssembly performance improvements

### PR DESCRIPTION
**Pull request by cooperra**
Most of these improvements are skipping setting Transform if the new value isn't different from the old one. This is surprisingly slow when there are lots of children.

The biggest bottleneck seemed to be `ConveyorAssembly`'s `_PhysicsProcess`, which adjusts all assembly parts. Ideally, we'd remove the whole thing and replace it with calls from setters and `NOTIFICATION_TRANSFORM_CHANGED` listeners. That way, it wouldn't run every frame.

The new solution is to pause assembly adjustments while the simulation is running. This seemed to be a good compromise. Most of the slowdown impact that I experienced was at simulation-time, not edit-time.

## Backup Workaround

You shouldn't need to do this anymore, but it's still possible. It would mostly be useful when the simulation isn't running and framerate is still too slow.

Select all `ConveyorAssembly`s that won't need adjusting and set `ProcessMode`to Disabled in the inspector for the whole selection. Everything will run much smoother, and all conveyors will continue to function.

Unfortunately, we need the `ConveyorAssembly` scripts to run on load so they can fix their appearance. So, either don't save the scene after doing the workaround or change `ProcessMode` back to Inherit if things ever look broken.

## Misc

Added more Jolt platforms.

### CODE REVIEW

**Comment by ryevdokimov** [comment]
>Still, performance during simulation didn't improve much for me. 

This was expected. See https://github.com/Open-Industry-Project/Open-Industry-Project/issues/59 for info about more optimizations.


>I'm not sure why the Jolt release I found didn't match the existing Windows binary

See: https://github.com/Open-Industry-Project/godot-jolt/commit/d6dbe05d736353f81d893926a7dcdffc76bdb0d4

To address these errors that show up after scaling: 
image

**Comment by ryevdokimov** [comment]
The `ConveyorEnd` subpart should probably be converted from using a RigidBody to a StaticBody as well to match everything else now.

image

**Comment by cooperra** [comment]
> > Still, performance during simulation didn't improve much for me.
> 
> This was expected. See #59 for info about more optimizations.

Based on my experiments so far, this isn't a rendering or physics problem. Removing all Roller meshes or bodies didn't impact performance much at all. It'll matter eventually, but it's not the current bottleneck.

Skipping all the code in `ConveyorAssembly`'s `_PhysicsProcess` is huge. Just pushed a change that pauses `ConveyorAssembly` updates while the simulation is running. Much smoother.

I'll look into building your Jolt fork next. I agree the errors are annoying.

**Comment by ryevdokimov** [comment]
>Skipping all the code in ConveyorAssembly's _PhysicsProcess is huge. Just pushed a change that pauses ConveyorAssembly updates while the simulation is running. Much smoother.

You lose the ability to modify the assemblies scale while the simulation is running though. 

This might be a necessary sacrifice at some point, but we'll still have to address the resulting suboptimal UX. Either we need to allow them to be resized still or to disable the scaling gizmo.

I think the latter is worth investigating. I already use the transform gizmo to freeze/unfreeze boxes (See: https://github.com/Open-Industry-Project/godot/commit/6e64dfc4e5a08d813f189eefb8aa56b42f612439). It should be possible to create an event for this in the fork. I even have an old proposal for this: https://github.com/godotengine/godot-proposals/issues/8445

**Comment by cooperra** [comment]
> This might be a necessary sacrifice at some point, but we'll still have to address the resulting suboptimal UX. Either we need to allow them to be resized still or to disable the scaling gizmo.

I see what I've done so far as a temporary fix. I'd consider scaling during simulation a lower-priority issue that we can get to later, unlike slow performance. Also, if you really need to, scaling will still resize the belt conveyors (stretch them), they will just be very ugly until you stop the simulation.

> I think the former is worth investigating. I already use the transform gizmo to freeze/unfreeze boxes (See: [Open-Industry-Project/godot@6e64dfc](https://github.com/Open-Industry-Project/godot/commit/6e64dfc4e5a08d813f189eefb8aa56b42f612439)). It should be possible to create an event when the gizmo is being used in the fork and use it to reenable the process. I even have an old proposal for this: [godotengine/godot-proposals#8445](https://github.com/godotengine/godot-proposals/issues/8445)

That's pretty cool. Yeah, I see the ideal solution being better change detection/tracking.

If you think this temporary fix is good enough for now, I'll create a new issue for the long-term fix.

**Comment by ryevdokimov** [comment]
>I'd consider scaling during simulation a lower-priority issue that we can get to later, unlike slow performance. 

Agreed.

>If you think this temporary fix is good enough for now, I'll create a new issue for the long-term fix.

Yeah, the main issues seem to be addressed. Please create a new issue to track the long-term solution.

**Comment by ryevdokimov** [comment]
Thanks!

**Pull request merged**
